import "@styles/globals.css";
import "react-datepicker/dist/react-datepicker.css";
import { Toaster } from "@components/ui/toaster";
import AuthProvider from "@providers/AuthProvider";
import type { Metadata } from "next";
import { Prompt } from "next/font/google";
import TanStackQueryProvider from "@providers/TanStackQueryProvider";

const prompt = Prompt({
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-background ${prompt.className}`}>
        <AuthProvider>
          <TanStackQueryProvider>
            <main>{children}</main>
            <Toaster />
          </TanStackQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
